- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    state: present

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - apt-transport-https
      - nginx

- name: Add docker's GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add the Docker repository to Apt sources.list
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable'
    state: present

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  ansible.builtin.user:
    name: admin
    groups: docker
    append: true

- name: Restart docker daemon
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker

- name: Create directories for kube files
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - backend
    - frontend

- name: Download minkube binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0700'
    group: admin
    owner: admin

- name: Add kubectl's GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add the kubectl repository to Apt sources.list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl

- name: Start minikube cluster
  ansible.builtin.command: minikube start
  become_user: admin
  become: true
  changed_when: "minikube_status.stdout or 'Running' in minikube_status.stdout"

- name: Create kube secret to allow access to github registry
  ansible.builtin.shell:
    cmd: kubectl create secret docker-registry dockerconfigjson-github-com \
                      --docker-server='{{ registry }}' \
                      --docker-username='{{ username }}' \
                      --docker-password='{{ token }}' \
                      --namespace='{{ namespace }}'
