apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080
  - name: metrics
    port: 9113
    targetPort: 9113
    nodePort: 30013
  selector:
    app: webserver
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          ports:
          - containerPort: 80
          image: nginx:latest
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
        - name: webexporter
          ports:
          - containerPort: 9113
          image: nginx/nginx-prometheus-exporter
          args: 
          - "-nginx.scrape-uri=http://localhost/nginx_status"
      volumes:
        - name: nginx-config
          configMap:
            defaultMode: 420
            name: webserver-conf 