apiVersion: v1
kind: ConfigMap
metadata:
  name: web-conf
  labels:
    app: prometheus-web
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "web"
        static_configs:
          - targets: 
              - webserver-service:9113