apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-service
  labels:
    app: kube-state-metrics
spec:
  type: NodePort
  ports:
  - name: prom
    port: 9090
    targetPort: 9090
    nodePort: 30001
  selector:
    app: kube-state-metrics
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prometheus-kube-deployment
  labels:
    app: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
        - name: prometheus-kube
          ports:
          - containerPort: 9090
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: ksm-conf  
