apiVersion: v1
kind: Service
metadata:
  name: prometheus-web-service
  labels:
    app: prometheus-web
spec:
  type: NodePort
  ports:
  - name: prom
    port: 9090
    targetPort: 9090
    nodePort: 30002
  selector:
    app: prometheus-web
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prometheus-web-deployment
  labels:
    app: prometheus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-web
  template:
    metadata:
      labels:
        app: prometheus-web
    spec:
      containers:
        - name: prometheus-web
          ports:
          - containerPort: 9090
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: web-conf  