name: 'App infrastructure deployment'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      server_ip: ${{ steps.terraform-output.outputs.output_ip }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Deploy app server
        id: terraform-output
        run: |
          terraform init
          terraform apply -auto-approve
          echo "output_ip=$(terraform output -raw server_ip)" >> "$GITHUB_OUTPUT"
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible
      - name: Update hosts file
        env:
          SERVER_IP: ${{ needs.terraform.outputs.server_ip }}
        working-directory: ./ansible
        run: echo "$SERVER_IP" >> hosts
      - name: Provide vault password
        working-directory: ./ansible
        run: echo "${{ secrets.VAULT_PASS }}" > secret.txt
      - name: Apply configuration
        working-directory: ./ansible
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY }}" 
          ansible-playbook -i hosts -u root --vault-password-file secret.txt playbook.yml
