name: 'Deploy app infrastructure'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform format
        run: |
          cd terraform
          terraform fmt -check
      - name: Terraform init
        run: |
          cd terraform
          terraform init
      - name: Terraform validate
        run: |
          cd terraform
          terraform validate
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
